astroconda/astroconda-contrib

- pyqtgraph/build.sh
- pyqtgraph/meta.yaml
The recipe uses `git_rev` to grab a specific commit hash, rather than building from HEAD. This prevents constant rebuilds.
Requirement of: #13
> Update pyqtgraph to latest "develop" build; with inline retag

- specviz/meta.yaml
@jhunkeler The current specviz really requires pyqtgraph version 0.9.11, which isn't in any distribution yet (pip/conda/etc). I had packaged it in my channel, but you can't set conda channels for dependency installs for anaconda.
Would it be possible to host the 0.9.11 version temporarily on astroconda?
> Update astroconda specviz package to latest version

- reftools/meta.yaml
- stsci-hst/meta.yaml
Remove deprecated pywcs package from the build
EDIT: The `reftools` package released in `stsci-hst` never required `pywcs` to begin with. Therefore it is safe to remove. No packages require `pywcs` (everything has switched over to `astropy.wcs`).
> Pywcs removal

- iraf/build.sh
- iraf/meta.yaml
`conda >4.2.1` deprecated `$CONDA_ENV_PATH` in favor of `$CONDA_PREFIX`. This change broke the `activate.d/iraf.sh` script for all users.
> Update iraf recipe to handle conda >4.2.1

- pyobjc-core/meta.yaml
- pyobjc-framework-cocoa/meta.yaml
- pyobjc-framework-quartz/meta.yaml
Previous downgrade was not required. The new metapackage requirement settings make this a safe choice once again.
> Reupgrade pyobjc to 3.1.1

- photutils/build.sh
- photutils/meta.yaml
Also removes so unused dependencies.
I left `d2to1` in `meta.yaml` in case you need it for your builds in some way, but strictly speaking `photutils` does not use `d2to1`.
> Update photutils to v0.2.2

- specviz/meta.yaml
Update `specviz` to RC5 so it will build in Python 3. Also see spacetelescope/specviz#212 and spacetelescope/specviz#213. c/c @nmearl
> Update specviz to RC5 so it will build in Python 3

- acstools/bld.bat
- acstools/build.sh
- acstools/meta.yaml
Updated acstools recipe to support 2.0.4:
* Bumped version to 2.0.4 (also see spacetelescope/acstools#8 and spacetelescope/acstools#10)
* Removed "deadly" `d2to1` hack in build scripts
* Removed unneeded dependencies from meta
@jhunkeler , if this breaks the build, please let me know and I'll update the PR. Thanks!
> Updated acstools recipe to support 2.0.4

- reftools/meta.yaml
Update `reftools` to 1.7.3 to fix build error due to accidentally importing optional import (`stsci.tools`).
> Update reftools to 1.7.3

- nictools/bld.bat
- pyraf/build.sh
- stsci.skypac/bld.bat
- stsci.skypac/build.sh
- wfpc2tools/build.sh
Does what it says on the box. Simply either remove 2to3 usage or silence its output completely, because the build logs are as indecipherable as they are gigantic.
> Remove or silence 2to3 execution

- verhawk/meta.yaml
Fixes python 2.7 build failure.
> Update verhawk v0.0.2

- calcos/meta.yaml
The build test completes successfully, but `--help` is not a valid option. Let's just print the version with `-r` instead.
> calcos: Use "-r" to print version instead of non-existent "--help"

- acstools/meta.yaml
This version of ACSTOOLS supports new ACS subarrays, so please merge ASAP. Thanks.
> Bumped acstools to 2.0.5

- pysynphot/meta.yaml
Upgrade `pysynphot` to 0.9.8.5 with bug fixes to `redshift()` method for `SourceSpectrum` and `Box` spectral element.
> Upgrade pysynphot to 0.9.8.5

- stsci/meta.yaml
Removes `webbpsf`, `webbpsf-data`, and `poppy` from the `stsci` metapackage. They will continue to be built and distributed, but not attached directly to the default user environment.
> Remove webbpsf and dependencies from base environment

- sextractor/build.sh
Final iteration. Builds were succeeding but not linking properly due to busted `"$OPTIONS"`
> sextractor no-quote options

- glue-vispy-viewers/LICENSE
- glue-vispy-viewers/meta.yaml
- glueviz/LICENSE
- glueviz/meta.yaml
- qtpy/LICENSE
- qtpy/meta.yaml
Here are updated recipes for glue v0.9 based on the versions in conda-forge. I also copied over the QtPy recipe since the version in the defaults channel is too old. Finally I also included the LICENSE files from the conda-forge recipes so everything is 'proper'.
**Note:** I think the glueviz and glue-vispy-viewers recipes will need to be built together since they inter-depend on each other.
cc @justincely @kassin
> Update glue to v0.9

- pyds9/build.sh
- pyds9/meta.yaml
The installation bug(s) in 1.8.x leave us no choice here. In local testing I haven't noticed any oddities with this 1.9.x development build, so I'm pushing it into the astroconda-channel.
I verified `pyds9-1.9.0.dev-61_g3761d7a` will be overwritten properly if/when the `pyds9-1.9.0` package is released, so we shouldn't have to worry about that when the time comes. 
Until then, I may update the `git_rev` periodically.
I removed the hard dependency on the `xpa` conda package. It doesn't conflict, however it isn't used either. In other words, there's no point in including it. If you want an independent XPA, then do `conda install xpa`, otherwise just use whatever is provided by `pyds9`.
Forcing the end-user to use libxpa provided by pyds9's source is unacceptable. Hopefully some day the …
> pyds9 1.8.1 -> 1.9.x master

- stsci-data-analysis/meta.yaml
@justincely I didn't notice these syntax errors on Friday. Merging the fix now.
> Fix spaces between match specifiers

- jwxml/bld.bat
- jwxml/build.sh
- jwxml/meta.yaml
- poppy/meta.yaml
- webbpsf/meta.yaml
~~**Note:** v0.1.0 is not yet tagged for mperrin/jwxml.~~
This makes WebbPSF and POPPY 0.5.1 available for AstroConda users. They're available in PyPI already.
> WebbPSF and POPPY v0.5.1

- glue-vispy-viewers/meta.yaml
- glueviz/meta.yaml
@justincely - this unpins the 3D viewers from PyQt4. Once this is merged, it would be great if you/others could test glue extensively (for any viewer, not just 3D) with PyQt5 to know if everything is working fine (there hasn't been much user testing on the Qt5 side)
> Update glueviz to 0.9.1 and glue-vispy-viewers to 0.6

- ginga/meta.yaml
Update Ginga to v2.6.0 (first GitHub release) -- https://github.com/ejeschke/ginga/releases/tag/v2.6.0
> Update Ginga to v2.6.0

- hstcal/build.sh
- hstcal/meta.yaml
@sosey discovered the HSTCAL build on OS X used `clang` instead of `gcc`, resulting in a segfault within `wfc3ir.e`.
This minor bump should take care of it.
> HSTCAL: Force gcc usage under OS X

- pyds9/meta.yaml
This avoids package clobbering as well.
> Ensure build string produces unique packages

- ginga/meta.yaml
Unable to build due to missing `qtpy` dependency. Also fixed the version data so the "v" prefix is no longer in the package name.
> ginga 2.6.1 (repair)

- stginga/meta.yaml
Bump `stginga` to 0.1.3 to be compatible with Ginga 2.6.1. Need this for AAS workshop on Jan 3, 2017.
Joe, do I need to add a "v" to the version? I am not sure if this should have the same convention as #128 or not.
> Bump stginga to 0.1.3

- stsci/meta.yaml
The `stsci` metapackage predates `stsci-data-analysis`, so we had `imexam` and `photutils` defined in two places. We're removing them from the top-level and letting the proper metapackage manage them from now on.
> Remove duplicated packages from stsci metapackage

- sphere/meta.yaml
Must update 1.0.10 to fix python 3.5 compilation failure on build system.
> Update sphere 1.0.7 -> 1.0.10

- ginga/meta.yaml
Missed or rebased/merged a `x.x` specifier into the `ginga` package; pre-overhaul.
> Fixup numpy requirement

- webbpsf-data/meta.yaml
(Not bumping the build revision -- data already exists in astroconda -- this problem was introduced by the overhaul)
> webbpsf-data: Fix broken URL

- stsci.tools/meta.yaml
Supersedes #132 
Bump `stsci.tools` to 3.4.3 to fix spacetelescope/stsci.tools#11
> Update stsci.tools 3.4.2.1 -> 3.4.3

- stsynphot/bld.bat
- stsynphot/build.sh
- stsynphot/meta.yaml
- synphot/bld.bat
- synphot/build.sh
- synphot/meta.yaml
Added recipes for Astropy version of PySynphot split into 2 packages: `synphot` and `stsynphot`
This requires Astropy 1.3. So, **do not merge** until AstroConda has that. Also, Joe, you should check that these actually can build, as `stsynphot` depends on `synphot` but I am adding both at the same time. They only have beta releases now but if beta does not work, then I can make a "stable" release.
> [EXP] Add refactored synphot and stsynphot

- stsynphot/meta.yaml
- synphot/meta.yaml
Invalid syntax:
`package >= 1.2.3`
Proper syntax:
`package >=1.2.3`
> Removes spaces between version specifiers

- stsynphot/meta.yaml
- synphot/meta.yaml
Resolver could not find `synphot >=0.1` due to the tag suffix `b2`. Appending a wildcard to the version specifier fixes the issue: `synphot >=0.1*`
@pllim fyi
> Fix resolver failure on "b" suffix.

- stsci.tools/meta.yaml
To be compatible with Astropy 1.3 or later.
> Bump stsci.tools to 3.4.4

- imexam/meta.yaml
This new release fixes a couple bugs, update xpa to v.2.1.18 and allows windows users to build without DS9 (Ginga is the viewer subsitute, or it can be used for command line interaction and making plots)
> update imexam to v0.7.0

- jwst_gtvt/meta.yaml
Should fix circular import error detected in the Python 2.7 build.
> jwst_gtvt -> 0.0.2

- stsci.tools/meta.yaml
To avoid deprecation warnings from astropy >= 1.3
> Bumped stsci.tools to 3.4.5

- ds9/build.sh
- ds9/meta.yaml
This optional dependency is missing on some machines (eg. my laptop running CentOS 7 and other cases we have seen with Ureka) at run time. It still seems to get compiled against libXss on MacOS, but that shouldn't really matter.
> Compile ds9 without libXss dependency on Linux & update to v7.5

- acstools/meta.yaml
To fix TypeError in regression test due to Numpy 1.12 indexing.
This fixes spacetelescope/acstools#20
> Bump acstools to 2.0.7

- stsci_sphinx_theme/meta.yaml
Without `setuptools` conda-build conveniently chooses the ROOT environment's `setuptools`. Gotta love it.
Without `python x.x` conda-build does a similar thing.
Winning all around.
> Add missing python requirements

- pysynphot/meta.yaml
Mainly for Numpy 1.12 compatibility.
Fixes astroconda/astroconda#53
> Bump pysynphot to 0.9.8.6

- glue-vispy-viewers/bld.bat
- glue-vispy-viewers/build.sh
- glue-vispy-viewers/meta.yaml
The inconsistent spaces in the recipe were throwing conda-build into a frenzy. `script: python setup.py install --single-version-externally-managed --record record.txt` seemed to be causing additional problems with conda's dependency resolution, so I removed it and added individual scripts.
What was added to `requirements/build` are the truly the bare minimum required to successfully compile this package. I don't recommend removing them.
BTW `preserve_egg_dir` acts much like `--single-version-externally-managed --record record.txt`, except for conda can actually track what's going on.
> Fix vispy viewers

- glue-ginga/bld.bat
- glue-ginga/build.sh
- glue-ginga/meta.yaml
Add `glue-ginga` package to the channel. This enables bridging between Glue and Ginga; that is, user can send data between the two software.
See https://github.com/ejeschke/glue-ginga/releases/tag/v0.1.1
c/c @ejeschke @astrofrog 
@jhunkeler , I am not 100% sure if the dependency listing would work properly, please test. Thanks!
> Add glue-ginga package to the channel

- ginga/meta.yaml
So it would work with `stginga`. This is basically pinning Ginga to latest dev as of today. There is not actually a real 2.6.2.1 release. @jhunkeler , is this the correct way to do such a thing?
> Quick fix for Ginga

- glue-core/LICENSE
- glue-core/meta.yaml
- glue-vispy-viewers/meta.yaml
- glueviz/meta.yaml
This updates the glue recipes to match the latest set-up - glueviz is now a metapackage that installs glue-core and stable plugins, which avoids circular dependencies.
The ``glue-core`` package should be built first since it doesn't yet exist, and it's needed for the glue-vispy-viewers package.
> Updates for glue

- astroquery/meta.yaml
For when 0.3.5 is actually released (soon). It will have Cone Search then.
Not sure why it was pointing to `spacetelescope`, it is an Astropy-affilliated package. How did that happen? Also, the actual GitHub release has a "v" in version number...
Also not sure about the PyPi incantations, probably needs changing too?
> Update Astroquery to 0.3.5

- crds/meta.yaml
Upgrade refers to:
https://github.com/spacetelescope/crds/pull/220
https://github.com/spacetelescope/crds/pull/221
https://github.com/spacetelescope/crds/pull/222
@jaytmiller Have there been any changes to the package dependencies between 7.1.0 and 7.1.1?
> crds -> 7.1.1

- calcos/meta.yaml
- crds/meta.yaml
- drizzlepac/meta.yaml
- hstcal/meta.yaml
- stsci-hst/meta.yaml
- stsci.tools/meta.yaml
- stwcs/meta.yaml
- wfc3tools/meta.yaml
Rolling back recipe changes to prevent automatic rebuilding and publication of errant packages created as part of the preparation for the HSTDP 2017.2 build, first iteration.
> Revert changes from HSTDP 2017.2

- parsley/meta.yaml
Corrected: `name = 'parsely'`
It would have helped to spell it right.
> parsley: Fix package naming typo

- crds/build.sh
- crds/meta.yaml
The new dependencies are not used except under certain specific circumstances. General users will not notice a difference.
> CRDS: Add optional dependencies; bump build

- drizzlepac/meta.yaml
Includes the following improvements:
- WCS merge logic for output WCS computations: https://github.com/spacetelescope/drizzlepac/pull/65
- addition of ``crpix1`` and ``crpix2`` parameters to TEAL for custom WCS: https://github.com/spacetelescope/drizzlepac/pull/66
- turned off memory mapping: https://github.com/spacetelescope/drizzlepac/pull/67
- updated release notes and ``htmlhelp``: https://github.com/spacetelescope/drizzlepac/pull/68
> Release drizzlepac 2.1.15

- htc_utils/meta.yaml
Fixes missing `git_tag`, and changes the repo URL to point to github instead of bitbucket.
> htc_utils: Fix tag and repo url

- drizzlepac/meta.yaml
Includes a fix for a bug in the mergeWCS logic due to which custom (=user specified) WCS scale parameter was ignored. See https://github.com/spacetelescope/drizzlepac/pull/69 for more details.
> Bump drizzlepac release to 2.1.16

- parsley/build.sh
README contains unicode characters and causes the build to fail on Linux. OS X seems to breeze through it.
> parsley: truncate README

- acstools/meta.yaml
Strictly speaking, `stsci.tools` is optional dependency because it is only used in *some* tasks in `acstools` but it is required for `acs_destripe_plus`, which is quite popular for people who use this package, so might as well just make it a dependency here to avoid resultant help calls.
> Make stsci.tools a depedency of acstools

- glue-ginga/meta.yaml
- mosviz/build.sh
* Adjust mosviz/setup.py on the fly to allow successful build
* Add missing dependency to glue-ginga
> Correct ripples from glue-related package shuffle

- acstools/meta.yaml
- calcos/meta.yaml
- drizzlepac/meta.yaml
- fitsblender/meta.yaml
- hstcal/meta.yaml
- pysynphot/meta.yaml
- stsci-data-analysis/meta.yaml
- stsci-hst/meta.yaml
- stsci.tools/meta.yaml
- stsci/meta.yaml
- stwcs/meta.yaml
- _CRDS rolls back to 7.1.1 from 7.1.3 (rebased out due to build delays. Trust me we built 7.1.1)
> HSTDP 2017.2

- spherical-geometry/meta.yaml
Match package name with existing PyPI package spherical-geometry. Decouple package name from repository name to accommodate previous naming decisions. (See https://github.com/spacetelescope/spherical_geometry/issues/104)
> Hyphenate package name

- acstools/meta.yaml
HSTDP does not use anything here (yet), so theoretically this can be merged anytime. I would like this to be merged as soon as possible, because `satdet` on AstroConda will not run properly with Astropy 2.0 until this is in.
c/c @dborncamp
> Bump ACSTOOLS to 2.0.9

- jwst_coronagraph_visibility/meta.yaml
Fixing two issues with the GUI:
https://github.com/spacetelescope/jwst_coronagraph_visibility/issues/15 - NIRCam A long-wavelength bar mask is flipped left-to-right in GUI
https://github.com/spacetelescope/jwst_coronagraph_visibility/issues/12 - Clear SIMBAD search field when user enters RA/Dec or chooses an example
> Update jwst_coronagraph_visibility to 0.3.0

- poppy/meta.yaml
* WavefrontError and subclasses now handle tilts and shifts correctly (#229, @mperrin) Thanks @corcoted for reporting!
* Fix the test_zernikes_rms test case to correctly take the absolute value of the RMS error, support outside= for hexike_basis, enforce which arguments are required for zernike(). (#223, @mperrin) Thanks to @kvangorkom for reporting!
* Bug fix for stricter Quantity behavior (UnitTypeError) in Astropy 2.0 (@mperrin)
* Added an optional parameter “mergemode” to CompoundAnalyticOptic which provides two ways to combine AnalyticOptics: mergemode="and" is the previous behavior (and new default), mergemode="or" adds the transmissions of the optics, correcting for any overlap. (#227, @corcoted)
* Add HexagonFieldStop optic (useful for making hexagon image masks for JWST WFSC, …
> Release POPPY 0.6.1

- drizzlepac/meta.yaml
Bug fixes and improvements included in 2.1.18:
https://github.com/spacetelescope/drizzlepac/pull/75 https://github.com/spacetelescope/drizzlepac/pull/80 and https://github.com/spacetelescope/drizzlepac/pull/82
> Make release 2.1.18

- glue-core/meta.yaml
- glue-vispy-viewers/bld.bat
- glue-vispy-viewers/build.sh
- glue-vispy-viewers/meta.yaml
- glueviz/meta.yaml
Replaces https://github.com/astroconda/astroconda-contrib/pull/220
These should be built in the following order: glue-core, glue-vispy-viewers, then glueviz
> Updated glue recipes to latest versions

- glue-ginga/meta.yaml
- glueviz/meta.yaml
* Fix circular dependency
* Remove metapackage build requirements 
* Investigation into behavior of conda-build 2.x vs conda-build 3.x indicates that using metapackages in recipe requirements may cause problems. Existing tool behavior and documentation suggests that this may not be a supported configuration.
* Increment build numbers
> Fix circular dependency; recipe standardization

- drizzlepac/meta.yaml
Fixed catalog doubling and catalog filtering issues in tweakreg. See https://github.com/spacetelescope/drizzlepac/pull/90 for more details.
CC: @rendinam
> Release drizzlepac v2.1.20

- stsci.skypac/meta.yaml
This release fixes a file open mode for temporary mask files to make code compatible with latest changes in astropy: see https://github.com/spacetelescope/stsci.skypac/pull/15 and https://github.com/spacetelescope/drizzlepac/issues/84 for more details.
CC: @rendinam @stsci-hack
> Release stsci.skypac v0.9.6

- stsci.skypac/meta.yaml
See https://github.com/spacetelescope/stsci.skypac/pull/19 for details. Fundamentally, version removal in v0.9.6 broke `skypac`.
> Bug fixes release v0.9.7

- asdf/meta.yaml
@rendinam In conda-dev, the resolver found `1.2.1` rather than `v1.3.1` as the latest version.  @drdavella has re-tagged the repository and dropped the "v" prefix.
> asdf: Dropped "v" prefix upstream

- drizzlepac/meta.yaml
This bug fix includes fixes for the following issues: https://github.com/spacetelescope/drizzlepac/issues/93, https://github.com/spacetelescope/drizzlepac/issues/94, and  https://github.com/spacetelescope/drizzlepac/issues/97
> Bug fix release 2.1.21 for drizzlepac

- acstools/meta.yaml
Fixes regression tests failing due to missing "optional" dependencies.
> Optional dependencies are no longer optional. Do not revert.

- stsci-hst/meta.yaml
BUGFIX: Prevent incompatible package, stwcs-1.4.0, from entering the py27 environment
> stsci-hst: lock stwcs version range under py27

- stsci-data-analysis/meta.yaml
- stsci-hst/meta.yaml
- stsci/meta.yaml
If runtime logic appears in a recipe specific to a certain version (or versions) of python, the Conda's selector logic will only be applied ONE TIME, using whichever version of python is active in the build environment.
Unacceptable.
> Avoid python-agnostic packages

- stsci.image/meta.yaml
The code in numcombine has been updated in https://github.com/spacetelescope/stsci.image/pull/4 Making a new release.
> Make stsci.image release 2.3.0 with updated numcombine

- cfitsio/build.sh
- cfitsio/meta.yaml
Allowing `libcfitsio` to link against the system's `libcurl` has undesired results on different OSes. Linking against Conda's `curl` should help, but I can't promise Continuum will not break it at some point.
**Note:** The recipe has been aligned with its -dev counterpart.
> Cfitsio: curl

- pysynphot/meta.yaml
Released today. Fresh and hot!
> Bump PySynphot to 0.9.10

- cubeviz/meta.yaml
- specviz/meta.yaml
These are (hopefully) the changes for the Cubeviz 0.2.0 release.  This release is dependent on:
* glue v0.13
* specviz 0.5
* specutils 'legacy-specutils'
* spectral-cube
Tom created is v0.13 release for Glue several hours ago and uploaded to his glue conda channel.  Nick created his 0.5 specviz release on Wednesday.
> Cubeviz 0.2.0 release

- pysiaf/bld.bat
- pysiaf/build.sh
- pysiaf/meta.yaml
pysiaf (https://github.com/spacetelescope/pysiaf ) implements Science Instrument Aperture File handling for space telescopes, in particular HST and JWST. It's on PyPI already but needs to be added to astroconda, which this PR does.
> add pysiaf recipe

- pysiaf/meta.yaml
Rambo fails with this otherwise:
```python
Traceback (most recent call last):
File "/Users/iraf/build/banana/workspace/AstroConda/public_OSX-10.11_py3.5_np1.11/_dispatch/miniconda/bin/rambo", line 11, in <module>
load_entry_point('rambo==1.0.0b5', 'console_scripts', 'rambo')()
File "/Users/iraf/build/banana/workspace/AstroConda/public_OSX-10.11_py3.5_np1.11/_dispatch/miniconda/lib/python3.5/site-packages/rambo-1.0.0b5-py3.5.egg/rambo/__main__.py", line 136, in main
File "/Users/iraf/build/banana/workspace/AstroConda/public_OSX-10.11_py3.5_np1.11/_dispatch/miniconda/lib/python3.5/site-packages/rambo-1.0.0b5-py3.5.egg/rambo/meta.py", line 197, in __init__
File "/Users/iraf/build/banana/workspace/AstroConda/public_OSX-10.11_py3.5_np1.11/_dispatch/miniconda/lib/python3.5/site-packages/rambo-1. …
```
> pysiaf: Add missing build number field

- stsci.skypac/meta.yaml
See https://github.com/spacetelescope/stsci.skypac/pull/23 and linked issues and PRs for more details.
> stsci.skypac release 0.9.12 - fix crash when 'matching'

- stsci.skypac/meta.yaml
See https://github.com/spacetelescope/stsci.skypac/pull/36 for more details.
Skipped v0.9.13 due to an incorrectly (prematurely) applied tag.
> Added optional parameters to PAM utilities in stsci.skypac

- ginga/meta.yaml
Fresh off the oven for Scipy 2018.
https://github.com/ejeschke/ginga/releases/tag/v2.7.1
> Bump Ginga to 2.7.1

- astropy-healpix/meta.yaml
This was previously accounting for an older broken release of setuptools.
> astropy-healpix: drop setuptools constraint

- stsci.imagemanip/meta.yaml
Fixes `stsci.tools.tester` incompatibility
https://github.com/spacetelescope/stsci.imagemanip/issues/9
https://github.com/spacetelescope/stsci.imagemanip/pull/10
> stsci.imagemanip: Update 1.1.2 -> 1.1.4

- pyregion/meta.yaml
- stsci-hst/meta.yaml
Replaced by `stregion`
Note: There's no reason to list `stregion` as a global dependency seeing as `drizzlepac` is the only package that depends on it.
> Deprecate pyregion

- ds9/meta.yaml
Build failed with old version errors on autotools components available on the usual linux build machine. This provides newer ones that let the build proceed.
> Add deps needed for use on default linux build machine.

- ci-watson/meta.yaml
To get rid of deprecation warnings.
> Bump ci-watson to 0.1.2

- crds/meta.yaml
CRDS-7.2.6 was tagged incorrectly so it's missing some key changes.  
Among other things this adds support for JWST REFTYPE=PSFMASK.
> Updated version to 7.2.8

- ci-watson/meta.yaml
Spooktacular release!
cc @jdavies-st -- `ci-watson` is in our `conda` channel here, so not sure what you mean by it is not available on `conda` for `jwst`.
> Bump ci-watson to 0.2

- drizzlepac/meta.yaml
It looks like release 2.2.5 was actually never released... So this release includes all the changes from `2.2.5` and `2.2.6` as described in the changelog, most important being fixing the units of output CR-cleaned (`'*_crclean.fits'`) images optionally produced by `drizzlepac` - see https://github.com/spacetelescope/drizzlepac/pull/190
CC: @rendinam
> Make release 2.2.6 of drizzlepac

- acstools/meta.yaml
In conjunction with 2018.3 delivery.
> Bump acstools to 2.1.0

- ginga/meta.yaml
For ADASS 2018 next week.
https://github.com/ejeschke/ginga/releases/tag/v2.7.2
> Bump Ginga to 2.7.2

- asdf/meta.yaml
Skipping the 2.2.0 release since there was a bug.
@rendinam I'm not sure how this works. It seems like #422 will need to be merged first, and then this one?
> Update to reflect ASDF v2.2.1 release

- conda_build_config.yaml
- stsci-data-analysis/meta.yaml
- stsci-hst/meta.yaml
- stsci/meta.yaml
* Remove totally deprecated dependencies
* Future: If recipe no longer exists... remove from metapackage
> Fix py37 package resolution failures

- stsci.imagestats/meta.yaml
- Python 3 conventions used during setup.
> stsci.imagestats: Disable python 2.7

- poppy/meta.yaml
Update for new poppy release version 0.8.0. 
Also, is this the right way to specify that poppy now requires Python 3.5 or greater?
> Update poppy to 0.8.0

- da5_notebooks/meta.yaml
Build system isn't keen on mismatches between underscores and hyphens
@larrybradley  affects SDN documentation
> da5_notebooks: Use underscore not hyphen

- da5_notebooks/meta.yaml
Reverts #447 to synchronize repository name with package name. I was able to build and install the package using this recipe locally. Am I missing something obvious?
> Reinstate hyphen in package/repo name.

- stsci-data-analysis/meta.yaml
~NO-MERGE~
* Remove non-stsci dependencies
* Temporarily disable `mosviz` and `specutils` (depends on what happens over the weekend, maybe?)
> da5: Modify minimum version requirements

- webbpsf/meta.yaml
Prevents users installing `stsci` from upgrading `numpy` beyond `1.14`
@mcara
> webbpsf: Remove jinga2 numpy var from run section

- astroscrappy/build.sh
- astroscrappy/meta.yaml
- ccdproc/build.sh
Updated recipes to fix python 3.7 conda build failures with the latest setup tools and ah_bootstrap.py
> Recipe updates to fix ah_bootstrap and setuptools

- ci-watson/meta.yaml
since ci-watson package will not build against atomicwrites 1.3.0 for some reason.
> Add pin of atomicwrites dependency of pytest to ci-watson

- spherical-geometry/meta.yaml
Fixed a bug dealing with `NAXIS1,2` deprecation, see https://github.com/spacetelescope/spherical_geometry/pull/165
CC: @jhunkeler
> NAXIS12->pixel_shape conversion

- acstools/meta.yaml
acstools 3.0.0 is already released on GitHub and PyPI. But I don't know if the release here needs to be coordinated with HSTDP delivery or not. I think the delivery that is happening right now will not use this version.
cc @nmiles2718 @mdlpstsci
> Bump acstools to 3.0.0

- tweakwcs/meta.yaml
See https://github.com/spacetelescope/tweakwcs/pull/69
As a by-product, C code is gone.
> tweakwcs v0.4.6: Improved initial (pre-matching) shift estimate

- jwst-visit-parser/bld.bat
- jwst-visit-parser/build.sh
- jwst-visit-parser/meta.yaml
I am trying to follow https://astroconda.readthedocs.io/en/latest/contributing.html. When testing the build locally with `conda build -c http://ssb.stsci.edu/astroconda --skip-existing --python=3.5 jwst-visit-parser` in preparation of this PR, I got an error related to the `atomicwrites` package which I am unable to resolve. 
I am attaching the traceback and the meta.yaml to this PR.
`atomicwrites` is not an explicit dependency of the new package and adding it to the build requirements in meta.yaml does not resolve or alter the problem.
> Add recipe for jwst-visit-parser

- wfpc2tools/meta.yaml
No code changes from 1.0.3 to 1.0.4. This removes the `.dev` suffix from the released code's version
> wfpc2tools (forgotten update 1.0.4)

- stsci-hst/meta.yaml
Package is archived. No one has been using it for quite some time. There is no reason to distribute it by default.
> Remove outdated/deprecated stsci.sphinxext from HST metapackage

- costools/meta.yaml
* No code changes. Removes .dev suffix from package version
> costools: update 1.2.3

- nictools/meta.yaml
* No code changes. Removes .dev suffix from package version
> nictools: update 1.1.4

- stsci.skypac/meta.yaml
This release improves `stsci.skypac` in the way it deals with images that almost entirely overlap on the sky by avoiding calling `spherical_geometry` methods in those cases. See https://github.com/spacetelescope/stsci.skypac/pull/49
> Reliability improvement in stsci.skypac

- mosviz/meta.yaml
```python
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all
dependencies in the meta.yaml  url=https://pypi.org/simple/setuptools_scm/
```
> mosviz: add setuptools_scm

- cubeviz/meta.yaml
```bash
checkout: 'v0.3'
error: pathspec 'v0.3' did not match any file(s) known to git.
Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
```
> cubeviz: use correct tag

- spectral-cube/meta.yaml
Attempting to fix `cubeviz` build:
```
Solving environment: ...working... failed
failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform linux-64: {"spectral-cube[version='>=0.4.4']", "pyqt5[version='<5.12']", 'cubeviz==0.3.0=py36_0'}
WARNING:conda_build.build:failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform linux-64: {"spectral-cube[version='>=0.4.4']", "pyqt5[version='<5.12']", 'cubeviz==0.3.0=py36_0'}
```
> spectral-cube -> 0.4.4

- pysynphot/meta.yaml
> Bump PySynphot to 0.9.13

- ci-watson/meta.yaml
The broken package that made the initial pin necessary has since been superseded by another build.
```
$ firewatch --time-span 1y | grep atomicwrites
2019-02-08T11:37:07 : main/noarch : atomicwrites-1.3.0-py_0.tar.bz2         
2019-03-22T17:18:14 : main/osx-64 : atomicwrites-1.3.0-py27_1.tar.bz2       
2019-03-22T17:21:19 : main/osx-64 : atomicwrites-1.3.0-py36_1.tar.bz2       
2019-03-22T17:21:44 : main/osx-64 : atomicwrites-1.3.0-py37_1.tar.bz2
```
Addresses #479 by reverting #478
> Remove pin of atomicwrites 1.2.1 in ci-watson recipe

- pysiaf/meta.yaml
This allows building against the dependencies that exist for py37.
> Relax openpyxl version pin in pysiaf

- webbpsf-data/meta.yaml
- webbpsf/meta.yaml
*2019 November 22*
Note, when upgrading to this version you will need to update to the latest data files as well. This is handled automatically if you use `conda`, otherwise you will need to download and install the data from: `webbpsf-data-0.9.0.tar.gz <https://stsci.box.com/shared/static/qcptcokkbx7fgi3c00w2732yezkxzb99.gz>`_.
**JWST Improvements**
- *Added a new capability to model the impact of thermal variations*, from telescope slews relative to the sun, onto mirror alignments and therefore onto PSFs. This new ``thermal_slew`` method  can be used to create a delta OPD for some elapsed time after the slew at either the maximum slew angle, some specified angle, or with a scaling factor applied to maximum case. Once combined with an input OPD (requirements or predicted), the new shape …
> WebbPSF v0.9.0

- webbpsf-data/meta.yaml
The server with the original `webbpsf-data` data link is being phased out in favor of _stsci.box_. The current link is downloading the wrong files due to an issue on the server side. 
CC @mperrin
> Urgent: Update the webbpsf-data Download Link 

- fitsverify/meta.yaml
Take advantage of conda-provided cfitsio package published in Nov 2019.
> Adjust cfitsio dependency version spec

- synphot/meta.yaml
in order to avoid creation of erroneous synphot-0.0.0.dist-info file.
> Add setuptools_scm to synphot build requirements

- hstcal/build.sh
- hstcal/meta.yaml
`gcc` package is no longer available from conda's channels.
Conda-supplied compilers used for linux.
OS-provided compilers are used for Macos.
> Update recipe to use operational toolchains

- astroquery/meta.yaml
- jwst_coronagraph_visibility/meta.yaml
Releasing new version of JWST Coronagraph Visibility Tool. Fixes bug in current conda install which prevents the program from running.
> Jwst coronagraph visibility 0.4.2

- pysiaf/meta.yaml
Updated `meta.yaml` file for `pysiaf` to include the new version number and the updated dependencies. 
Previous ran `conda build -c http://ssb.stsci.edu/astroconda --skip-existing --python=3.6 pysiaf` for both python 3.6 and 3.7 and they both passed without error.
> Update pysiaf to v0.7.1

- drizzlepac/meta.yaml
Update `drizzlepac` recipe to allow building on Linux and Macos.
> HSTDP-2019.5.1-final

- jwst_coronagraph_visibility/meta.yaml
- Updated to CVT to use pysiaf 0.7.1 which uses PRD PRDOPSSOC-027.
- Fixed mac bundle issue (app would not open) from previous release.
- Updated unit tests to reflect changes from SIAF in PRDOPSSOC-027.
> Releasing JWST Coronagraph Visibility Tool version 0.4.4

- hstcal/meta.yaml
It's required by the build tool 'waf'. This will help make requirements more explicit and enforce consistency of which python is used in the build environment.
> Add python as an hstcal build dependency

- reftools/meta.yaml
https://github.com/spacetelescope/reftools/releases/tag/2.0.0
> Bump reftools to 2.0

- asdf/meta.yaml
We released asdf 2.5.2, which no longer requires `six` as a dependency.
> Release asdf 2.5.2 and remove dependency on six

- cfitsio/meta.yaml
- fitsverify/meta.yaml
- hstcal/meta.yaml
Build cfitsio 3.470 patched to avoid curl
Rebuild fitsverify to use above
Rebuild hstcal to use above
> cfitsio update and multi-package rebuild

- hstcal/build.sh
It's not on the PATH within the Jenkins job.
> Explicitly define gfortran location in hstcal build

- specutils/meta.yaml
It has always been a dependency (since the `AsdfExtension` was added) but has been pulled in via `gwcs`.  It is now a package dependency in `setup.cfg` and needs to be reflected here as well.
> Add asdf to package dependencies

- cfitsio/meta.yaml
- fitsverify/meta.yaml
* Also adjust toolchain specification for cfitsio to match approach taken by hstcal. Use OS-supplied compiler on Macos, use conda-supplied compiler on Linux.
> Add bzip2 dep to cfitsio. Request rebuild of fitsverify to sync.

- stsci.skypac/meta.yaml
Bug Fix Release: polygon filling algorithm. See https://github.com/spacetelescope/stsci.skypac/pull/52 and https://github.com/spacetelescope/stsci.skypac/pull/55.
Also:
- Remove `relic`: https://github.com/spacetelescope/stsci.skypac/pull/53
- Pep8 and docstrings: https://github.com/spacetelescope/stsci.skypac/pull/54 and https://github.com/spacetelescope/stsci.skypac/pull/56
CC: @jhunkeler @rendinam 
Also, PyPi
> Release stsci.skypac v1.0.5

- acstools/meta.yaml
https://github.com/spacetelescope/acstools/releases/tag/3.2.0
cc @jryon @nmiles2718
> Bump acstools to 3.2.0

- pysiaf/meta.yaml
I updated the `pysiaf` version in `meta.yaml` to `0.8.0` for the new release.
I did have one issues I just wanted to note:
I originally ran `conda build -c http://ssb.stsci.edu/astroconda --skip-existing --python=3.6 pysiaf` and it failed, telling me that "RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.org/simple/et-xmlfile/". So I added `et-xmlfile` (and `setuptools` for good measure) to the `yaml` file despite the fact the `et_xmlfile` was already listed in the "packages to be installed". This made the check pass and build the package, but only after seemingly installing `et-xmlfile` twice and then clobbering the multiple installations. I'm not sure if that's an issue, but the the `conda build` check is …
> Update pysiaf to v0.8.0

- pysiaf/meta.yaml
This PR updates the `meta.yaml` file for `pysiaf` to version 0.9.0. I tested this change with the command `conda build -c http://ssb.stsci.edu/astroconda --skip-existing --python=3.6 pysiaf` for python 3.6 and 3.7 and the package built successfully for both cases.
> Update pysiaf package to v0.9.0

- poppy/meta.yaml
- webbpsf/meta.yaml
Updating `WebbPSF` and `Poppy` `meta.yaml` files for version 0.9.1 patch release. We are not releasing a new version of `webbpsf-data` with this patch, so that information was left unchanged.
I ran the `conda build` command for both `webbpsf` and `poppy` and both passed without error
cc @mperrin
> Update WebbPSF and Poppy for v0.9.1

- stsci.imagestats/meta.yaml
Apparently this package has been building `master` in whatever state its in, for however long.
> stsci.imagestats use a tag

- asdf/meta.yaml
asdf 2.7.0 is released.  This version drops support for jsonschema 2.x, and we've moved the repository to a new GitHub organization.
> Release asdf 2.7.0, update requirements and GitHub URL

- pyds9/meta.yaml
Ref #628. This is to pickup the latest commits with the six fix, otherwise the package crashes with recent astropy versions.
> Update pyds9 to the latest master commit

- gwcs/meta.yaml
Note that it requires astropy 4.1. Not sure if this is a problem for astroconda.
> bump gwcs to 0.15.0

- tweakwcs/meta.yaml
Added support for `rshift` fitting mode - see https://github.com/spacetelescope/tweakwcs/pull/128
> Make tweakwcs release 0.7.0

- pysiaf/bld.bat
- pysiaf/build.sh
- pysiaf/meta.yaml
Add missing dependency `et_xmlfile`. 
`pysiaf` does not list this as a requirement itself.
> pysiaf: stop building as egg

- semantic_version/meta.yaml
Recipes need to specify under `host` or `build`, `- python {{ python }}` so the correct interpreter is utilized at compile-time
> semantic_version: Fix missing python requirement

- extension-helpers/meta.yaml
> extension-helpers: Add missing python requirement

- sphinx-automodapi/meta.yaml
> sphinx-automodapi: Add missing python requirement

- gwcs/meta.yaml
The build doesn't work and has been failing for a very long time.
> gwcs: disable py36

- stsci.skypac/meta.yaml
Switch to using `bitmask` module from `stsci.tools` to `astropy.nddata`. See https://github.com/spacetelescope/stsci.skypac/pull/61
> Release 1.0.6 - package maintenance

- pysynphot/meta.yaml
- stsynphot/meta.yaml
- synphot/meta.yaml
Triple play!
* https://github.com/spacetelescope/pysynphot/releases/tag/1.0.1
* https://github.com/spacetelescope/synphot_refactor/releases/tag/1.1.0
* https://github.com/spacetelescope/stsynphot_refactor/releases/tag/1.1.0
People will want to use these with `astropy` 4.3 that is coming out soon.
> MNT: Bump synphotses

- stsci.skypac/meta.yaml
Effectively undoes https://github.com/spacetelescope/stsci.skypac/pull/61
Switch back to using bitmask module from stsci.tools. See  https://github.com/spacetelescope/stsci.skypac/pull/62
> Package maintenance. Release skypac 1.0.7

- stsci.image/meta.yaml
Minor code clean up to deal with `numpy` deprecation warnings.
> Release stsci.image 2.3.4

- stsci.skypac/meta.yaml
Fix deprecation warnings from `numpy` due to use of `numpy` aliases to fundamental Python data types. See https://github.com/spacetelescope/stsci.skypac/pull/63 for more details.
> Maintenance release of stsci.skypac v1.0.8

- pysynphot/meta.yaml
Bump PySynphot to 2.0.0 for Python 3 only.
> Bump PySynphot to 2.0.0

- jwebbinar_prep/build.sh
- jwebbinar_prep/meta.yaml
This conda package is needed to deliver the JWebbinar notebooks in DE Build E.
> Add recipe for jwebbinar notebooks

- drizzlepac/meta.yaml
Update yaml file to install Drizzlepac v3.3.0, and update requirements based what is needed for the new features in v3.3.0.
> Release Drizzlepac v3.3.0

- synphot/meta.yaml
synphot 1.1.1 is needed to be compatible with astropy 5.0.
> Bump synphot to 1.1.1

- poppy/meta.yaml
- webbpsf-data/meta.yaml
- webbpsf/meta.yaml
Changes cover `poppy`, `webbpsf`, and `webbpsf-data`.
I switched away from using the `{{ numpy }}` variable because our minimum required version (1.18.0) is now higher than the one specified in `conda_build_config.yaml` (1.14). If there's a better solution, please let me know.
> WebbPSF and poppy v1.0.X updates

- pysiaf/meta.yaml
Still need to test install, are there a set of instructions `astroconda` likes to follow? I would like to test `pysiaf` to make sure the package version updates install correctly.
I attempted:
`conda build -c http://ssb.stsci.edu/astroconda --skip-existing --python=3.7 pysiaf`
I ended up getting an error:
`ImportError: cannot import name 'get_index' from 'conda.api'`
> Updating pysiaf to v0.14.0

- reftools/meta.yaml
https://github.com/spacetelescope/reftools/releases/tag/2.1.0
> Bump reftools to 2.1.0
