- asdf/bld.bat
- asdf/build.sh
- asdf/meta.yaml
> Update asdf 1.0.2 -> 1.0.3

- poppy/meta.yaml
- webbpsf-data/meta.yaml
- webbpsf/meta.yaml
new release of webbpsf & poppy. This PR is just straightforward updates to version numbers in the yaml files.
> update poppy, webbpsf, webbpsf-data to 0.5.0

- pyfftw/meta.yaml
- pyneb/meta.yaml
- pyraf/meta.yaml
- pytools/meta.yaml
- stsci-data-analysis/meta.yaml
- stsci-hst/meta.yaml
- stsci.sphere/meta.yaml
- stsci/meta.yaml
A more organic solution to the metapackage locking issue we've been seeing.
> Free range packages

- calcos/meta.yaml
These changes relate to hstdp-2016.1
> Update calcos -> 3.1.8

- crds/meta.yaml
> Update crds -> 7.0.1; revamp recipe

- hstcal/meta.yaml
> Update hstcal -> 1.0.1

- stginga/meta.yaml
Update stginga to 0.1.1 bug fix release.
Also see https://github.com/spacetelescope/stginga/releases/tag/0.1.1
> Update stginga 

- pysynphot/meta.yaml
Update pysynphot to 0.9.8.3, as requested by @jhunkeler
> Update pysynphot to 0.9.8.3

- pyds9/meta.yaml
* Fixed bad tag reference
* Bumped build number
> Update pyds9 recipe

- stginga/meta.yaml
Bump `stginga` to 0.1.2.
NOTE: Also see STScI-JWST/wss_tools#7
> Bump stginga to 0.1.2

- specutils/bld.bat
- specutils/build.sh
- specutils/meta.yaml
Blocks #36 
Waiting on new tag data.
> Initial commit of specutils

- specviz/meta.yaml
@jhunkeler this also requires the specutils package be in astroconda as well. It's an astropy package: [https://github.com/astropy/specutils](https://github.com/astropy/specutils). If you need me to put together a meta file, let me know!
> Update astroconda specviz package to latest version

- aprio/meta.yaml
As well as fixed recipe dependencies
> Update aprio 1.0 -> 1.0.1

- ginga/meta.yaml
Bumped Ginga to 2.5.20160801083400. Also added command line test.
> Bumped Ginga to 2.5.20160801083400

- reftools/bld.bat
- reftools/build.sh
- reftools/meta.yaml
Update reftools to 1.7.2. Also cleaned up the relevant files.
> Update reftools to 1.7.2

- pyraf/meta.yaml
Bump PyRAF version to 2.1.11. Fixes #52. c/c @cdsontag
> Bump PyRAF version to 2.1.11

- verhawk/bld.bat
- verhawk/build.sh
- verhawk/meta.yaml
Used by https://github.com/STScI-JWST/jwst/pull/177
(Or at least it _will_ be used in AstroConda at some point)
> Add verhawk v0.0.1

- pandokia/meta.yaml
Forgot to bump the build revision number in the previous update.
> pandokia: bump build revision

- wfc3tools/bld.bat
- wfc3tools/build.sh
- wfc3tools/meta.yaml
Requesting to update the release package in astroconda to 1.3.3 for spacetelescope/wfc3tools
> update wfc3tools to 1.3.3

- ginga/meta.yaml
Updated Ginga to latest dev to include new table viewer and plotter.
> Update Ginga to 2.5.20161005204600

- astroimtools/meta.yaml
Bump astroimtools to 0.1.1. Need this for Nov workshop.
> Bump astroimtools to 0.1.1

- imexam/bld.bat
- imexam/build.sh
- imexam/meta.yaml
- Revamp recipe
- update to 0.6.2
- add/remove/move dependencies
cc @justincely 
This will be available tomorrow morning.
> Update imexam -> 0.6.2

- specviz/meta.yaml
Update astroconda specviz package to latest version.
> SpecViz update

- photutils/meta.yaml
This version is needed for the JWST workshop this week.
> Update photutils to v0.3

- astroquery/bld.bat
- astroquery/build.sh
- astroquery/meta.yaml
@jhunkeler  - we'd like to have this in place for the workshop tomorrow, would it be possible to build this today? It's pure Python, so takes <1 minute to build. Thanks!
cc @eteq
> Add recipe for astroquery

- mosviz/bld.bat
- mosviz/build.sh
- mosviz/meta.yaml
- stsci-data-analysis/meta.yaml
> Add first mosviz release, closes #78

- hstcal/meta.yaml
DP approved it for installation. Same as 1.1.1rc1.
> Bumped HSTCAL version to 1.1.1

- ginga/meta.yaml
Upgrade ginga to include workshop bugfix. If someone can merge this ASAP so it is ready for workshop tomorrow (Nov 10), that would be very nice. Thanks!
> Upgrade ginga to include workshop bugfix

- mosviz/meta.yaml
- specviz/meta.yaml
> Tag changed from under itself. 

- stsci.convolve/meta.yaml
stsci.convolve's missing updates
> Update stsci.convolve 2.1.3 -> 2.2.0

- ginga/meta.yaml
Update Ginga to include latest bug fix on Nov 10 for the workshop.
> More Ginga bug fix

- wfc3tools/meta.yaml
> update wfc3tools to version 1.3.4

- stsci.tools/meta.yaml
Update `stsci.tools` to 3.4.2.1. Fix homepage. c/c @cdsontag
> Update stsci.tools to 3.4.2.1

- stwcs/meta.yaml
> update stwcs to 1.2.5

- ginga/meta.yaml
See https://github.com/ejeschke/ginga/releases/tag/v2.6.1 for release notes
> Bump Ginga to 2.6.1

- imexam/meta.yaml
new version tagged and released
> update imexam to 0.6.3

- stsci-hst/meta.yaml
Package didn't build -- leaving version data alone
> Fix missing "set" keyword in jinja template

- jwxml/meta.yaml
- sextractor-generic/meta.yaml
- stsci.ndimage/meta.yaml
- webbpsf/meta.yaml
- ws4py/meta.yaml
More missing 'set' keywords in variable declarations.
> Fix invalid jinja declarations

- gwcs/meta.yaml
> Reverts downgrade of gwcs due to rebase

- drizzle/meta.yaml
Update required for python3.5 build
> Update drizzle 1.1 -> 1.5

- drizzle/meta.yaml
> Remove version prefix

- stwcs/meta.yaml
Avoids duplicate package warning.
> stwcs bump build revision

- fitsblender/meta.yaml
> Update fitsblender -> 0.3.0

- jwst_gtvt/bld.bat
- jwst_gtvt/build.sh
- jwst_gtvt/meta.yaml
Pushing through despite build issues with Python 2.7.
They will be addressed at a later time.
Python 3.x builds seem to be OK.
> Initial commit of jwst_gtvt

- imexam/meta.yaml
- bugfix release for the imexam package
> update imexam to v0.7.1

- acstools/meta.yaml
> Bump acstools to 2.0.6

- stsci_sphinx_theme/bld.bat
- stsci_sphinx_theme/build.sh
- stsci_sphinx_theme/meta.yaml
@jhunkeler  No more weird commits in this one.
> Theme addition

- fitsverify/bld.bat
- fitsverify/build.sh
- fitsverify/meta.yaml
@jaytmiller Adding fitsverify per your request
> Initial commit of fitsverify

- ginga/meta.yaml
See https://github.com/ejeschke/ginga/releases/tag/v2.6.2
> Bump Ginga to 2.6.2

- glue-vispy-viewers/meta.yaml
- glueviz/meta.yaml
Let me know if there are any issues with these updated recipes!
> Update glueviz to 0.10 and glue-vispy-viewers to 0.7.1

- fitsverify/meta.yaml
> Fix incorrect pkg-config dep; bump build

- ccfits/build.sh
- ccfits/meta.yaml
> Initial commit of CCfits 2.5

- glue-vispy-viewers/meta.yaml
- glueviz/meta.yaml
Remove circular dependency from glueviz; other minor adjustments to allow isolated building of these packages to succeed.
> Dependency adjustments

- stsci.tools/meta.yaml
https://github.com/spacetelescope/stsci.tools/pull/30
https://github.com/spacetelescope/stsci.tools/pull/29
> Upgrade stsci.tools -> 3.4.6

- drizzlepac/meta.yaml
https://github.com/spacetelescope/drizzlepac/pull/44
https://github.com/spacetelescope/drizzlepac/pull/43
> Upgrade drizzlepac -> 2.1.9

- stsci.skypac/meta.yaml
https://github.com/spacetelescope/stsci.skypac/pull/8
> Upgrade stsci.skypac -> 0.9.2

- drizzlepac/meta.yaml
- Added `stsci.tools` dependency
> Update drizzlepac -> 2.1.10

- stsci.skypac/meta.yaml
> Upgrade stsci.skypac -> 0.9.4

- drizzlepac/meta.yaml
Same reasons as #190 and #189 and #188
> Upgrade drizzlepac -> 2.1.11

- photutils/meta.yaml
Also add `scikit-learn` as a new (optional) dependency.
> Update photutils to 0.3.2

- ginga/meta.yaml
https://github.com/ejeschke/ginga/releases/tag/v2.6.3
> Bump Ginga to latest release

- stsci.tools/meta.yaml
https://github.com/spacetelescope/stsci.tools/pull/31
Internal tests passed.
> Upgrade stsci.tools -> 3.4.7

- drizzlepac/meta.yaml
> Upgrade drizzlepac -> 2.1.12

- drizzlepac/meta.yaml
Fix logic used to turn sky subtraction off
> Upgrade drizzlepac -> 2.1.13

- stsci.skypac/meta.yaml
> Version bump to 0.9.5: Explicitly set memory mapping to False

- purge_path/meta.yaml
- Changes git repository URL as wel
> purge_path 1.0.0 -> 1.2.0

- jwxml/meta.yaml
Release the jwxml 0.3.0 with SIAF files from PRDOPSSOC-F-008.
> jwxml 0.3.0

- stsci.tools/meta.yaml
Refers to:
- https://github.com/spacetelescope/stsci.tools/pull/37
- https://github.com/spacetelescope/stsci.tools/pull/36
> Update stsci.tools -> 3.4.10

- ginga/meta.yaml
This is needed for `wss_tools` to run properly.
Fix STScI-JWST/wss_tools#25
> Ginga: Bug fix release based on dev

- drizzlepac/meta.yaml
Corrected invalid tag on 2.1.16 (upstream)
> drizzlepac: bump revision

- ginga/meta.yaml
See https://github.com/ejeschke/ginga/releases/tag/v2.6.4
> Bump Ginga to 2.6.4

- pysynphot/meta.yaml
- stsynphot/meta.yaml
- synphot/meta.yaml
Bump beta of refactored versions in anticipation of Astropy v2. Added `pytest` to all three.
> Bump beta versions of synphot and stsynphot

- crds/meta.yaml
Eventually to support JWST cal code concurrent CRDS cache syncs.
> Add CRDS dependency on lockfile

- jwst_footprints/bld.bat
- jwst_footprints/build.sh
- jwst_footprints/meta.yaml
@leonardoubeda Package has been added.
> Initial commit of jwst_footprints

- stginga/meta.yaml
Please merge as soon as you know it is not breaking stuff, so I can inform QUIP people.
> Bump stginga to 0.2.1

- ginga/meta.yaml
See https://github.com/ejeschke/ginga/releases/tag/v2.6.5
> Bump Ginga to 2.6.5

- hstcal/meta.yaml
> HSTCAL 1.2.0 -> 1.3.0

- spherical-geometry/meta.yaml
To be consistent with conda-forge/staged-recipes#3388 and PyPi. c/c @bernie-simon
> Bump spherical-geometry to 1.0.12

- py-expression-eval/bld.bat
- py-expression-eval/build.sh
- py-expression-eval/meta.yaml
> Initial commit of py_expression_eval

- cfitsio/meta.yaml
* also to standardize for future archive file versions
> Adjust URL to allow download on all hosts 

- webbpsf-data/meta.yaml
- webbpsf/meta.yaml
> Release WebbPSF 0.6.0

- jwst_footprints/meta.yaml
Ref: https://github.com/spacetelescope/jwst_footprints/pull/5
> [jwst_footprints] 1.2.0 -> 2.2.0

- specviz/meta.yaml
> Update SpecViz package

- pyobjc-core/build.sh
- pyobjc-framework-cocoa/build.sh
- pyobjc-framework-quartz/build.sh
Cherry-picked from https://github.com/astroconda/astroconda-dev/pull/70
> pyobjc: Enforce rpath padding (#70)

- crds/meta.yaml
2017.3 delivery: https://github.com/astroconda/astroconda-releases/pull/11
> CRDS 7.1.4 -> 7.1.5

- drizzlepac/meta.yaml
Fix integer division in tweakreg. See https://github.com/spacetelescope/drizzlepac/pull/86 for more details.
> Make drizzlepac v2.1.19 release.

- dbus-glib/build.sh
- dbus-glib/meta.yaml
* Initial commit; dbus-glib
* Skip package host is not Linux; add selinux note
* Remove worthless argument
> Initial commit; dbus-glib (#58)

- dbus-python/bld.bat
- dbus-python/build.sh
- dbus-python/meta.yaml
* Initial commit; dbus-python
* Update meta.yaml
* Skip package if host is not Linux
> Initial commit; dbus-python (#57)

- secretstorage/bld.bat
- secretstorage/build.sh
- secretstorage/meta.yaml
* Initial commit; secretstorage
* Skip if host is not linux
* Remove commentary track
> Initial commit; secretstorage (#56)

- astroquery/build.sh
- astroquery/meta.yaml
* Initial commit; astroquery
* Only install secretstorage on linux
Requires: #265 #266 #267
> Initial commit; astroquery (#59)

- stsci.skypac/meta.yaml
See https://github.com/spacetelescope/drizzlepac/issues/91 for more details.
CC: @rendinam
> Fixed version import error and bumped skypac's version

- ginga/meta.yaml
See https://github.com/ejeschke/ginga/releases/tag/v2.6.6
> Bump Ginga to 2.6.6

- specviz/meta.yaml
Update SpecViz from v0.4.1 to v0.4.2.
> Update astroconda specviz package

- specviz/meta.yaml
Please do ASAP for conference.
> Update astroconda specviz packages

- gwcs/meta.yaml
> release gwcs 0.8.0

- jwst_gtvt/meta.yaml
This includes support for moving targets.  It would be good to get it in for the "Planning Solar System Observations with JWST" 12/13/17-12/15/17.
> new version of jwst_gtvt

- asteval/meta.yaml
- cubeviz/bld.bat
- cubeviz/build.sh
- cubeviz/meta.yaml
> Contrib cubeviz & asteval

- stsynphot/meta.yaml
- synphot/meta.yaml
https://github.com/spacetelescope/synphot_refactor/releases/tag/0.1
https://github.com/spacetelescope/stsynphot_refactor/releases/tag/0.1
> Bump synphot and stsynphot to 0.1

- astroquery/meta.yaml
https://github.com/astropy/astroquery/releases/tag/v0.3.7
> Bump astroquery to 0.3.7

- stsci.tools/meta.yaml
x-ref: https://github.com/spacetelescope/stsci.tools/issues/63
> stsci.tools: 3.4.11 -> 3.4.12

- costools/meta.yaml
- drizzlepac/meta.yaml
- nictools/meta.yaml
#308 #307 - Introduced the need for recipes to use `d2to1` and `stsci.distutils` directly.
> Fixup d2to1 recipes

- radio-beam/bld.bat
- radio-beam/build.sh
- radio-beam/meta.yaml
> Initial commit of radio-beam

- spectral-cube/bld.bat
- spectral-cube/build.sh
- spectral-cube/meta.yaml
Required by `specviz` and other `viz`-like packages
> Initial commit of spectral-cube

- ginga/meta.yaml
- stginga/meta.yaml
> Bump Ginga to 2.7 and stginga to 0.3

- pysynphot/meta.yaml
Here is the release, @rendinam and @ibusko.
> Bump PySynphot to 0.9.9

- asdf/meta.yaml
To be consistent with https://pypi.python.org/pypi/asdf
c/c @drdavella
> Bump asdf release to 1.3.3

- drizzlepac/meta.yaml
See main changes: https://github.com/spacetelescope/drizzlepac/pull/104, https://github.com/spacetelescope/drizzlepac/pull/107, https://github.com/spacetelescope/drizzlepac/pull/112 and https://github.com/spacetelescope/drizzlepac/pull/113
> Drizzlepac release 2.1.22: Improved create median step. Updated documentation

- pyraf/meta.yaml
> Bump PyRAF to 2.1.14

- drizzlepac/meta.yaml
See https://github.com/spacetelescope/drizzlepac/pull/126
CC: @jhunkeler
> Fix a bug in processing input files in TweakReg

- pysynphot/meta.yaml
I take rolling release to the extreme.
> Bump pysynphot 0.9.11

- pysynphot/meta.yaml
> Bump pysynphot to 0.9.12

- stsci.skypac/meta.yaml
See https://github.com/spacetelescope/stsci.skypac/issues/27 and https://github.com/spacetelescope/stsci.skypac/pull/28
> Added utilities for generating Pixel Area Maps

- crds/meta.yaml
The diffs show what I'm trying to accomplish.   IIRC more changes are needed so I may need help with this pull request.
> Updated CRDS release to 7.2.2 from spacetelescope/crds.

- cubeviz/meta.yaml
> cubeviz: add missing dependency

- stsci.skypac/meta.yaml
Ref: https://github.com/spacetelescope/stsci.skypac/pull/31
> stsci.skypac: 0.9.10 -> 0.9.11

- drizzlepac/bld.bat
- drizzlepac/build.sh
- drizzlepac/meta.yaml
> drizzlepac: 2.2.2 -> 2.2.3

- spherical-geometry/meta.yaml
> New spherical geometry release

- pyraf/meta.yaml
> Bump PyRAF to 2.1.15

- gwcs/meta.yaml
> gwcs: drop 2.7

- asdf/meta.yaml
> asdf: drop 27 support

- stregion/bld.bat
- stregion/build.sh
- stregion/meta.yaml
ref: https://github.com/spacetelescope/drizzlepac/issues/163
> Initial commit of stregion

- drizzlepac/meta.yaml
See https://github.com/spacetelescope/drizzlepac/issues/163
> Switch drizzlepac to using stregion

- stsci.skypac/meta.yaml
See https://github.com/spacetelescope/stsci.skypac/pull/37
> Enhancements to Pixel Area Map computation

- stsynphot/meta.yaml
Timing with GSR is just a coincidence...
> Bump stsynphot to 0.1.1

- synphot/meta.yaml
> Bump synphot to 0.1.2

- photutils/meta.yaml
This version requires python 3.5+.
> Update photutils to v0.5

- cfitsio/0001-cfitsio-autoconf-disable-curl.patch
- cfitsio/build.sh
- cfitsio/meta.yaml
- crds/meta.yaml
- fitsverify/meta.yaml
- hstcal/build.sh
- hstcal/meta.yaml
- stsci/meta.yaml
Ref:
https://github.com/spacetelescope/hstcal/issues/325
> cfitsio: disable cURL

- semantic_version/bld.bat
- semantic_version/build.sh
- semantic_version/meta.yaml
> Initial commit of semantic_version

- ci-watson/bld.bat
- ci-watson/build.sh
- ci-watson/meta.yaml
https://pypi.org/project/ci-watson/
https://github.com/spacetelescope/ci_watson/releases/tag/0.1
> Add ci-watson

- calcos/build.sh
> Remove sed from calcos build

- ci-watson/meta.yaml
> Bump ci-watson to 0.1.1

- stsci.imagestats/meta.yaml
See https://github.com/spacetelescope/stsci.imagestats/pull/6
> Fix handling of limits

- astropy-healpix/meta.yaml
- astroscrappy/build.sh
- astroscrappy/meta.yaml
- ccdproc/meta.yaml
- reproject/build.sh
- reproject/meta.yaml
* The following packages have serious issues with 3.7...
* astroscrappy refuses to compile due to incompatible C code
* ccdproc refuses to compile due to astroscrappy's failure to build
> Aggressive compatibility sweep

- specutils/meta.yaml
> Update specutils to v0.5.1

- asteval/meta.yaml
- specviz/meta.yaml
> Update specviz version

- tweakwcs/bld.bat
- tweakwcs/build.sh
- tweakwcs/meta.yaml
This is a new package.
CC: @mcara
> Add tweakwcs 0.1.1

- webbpsf-data/build.sh
- webbpsf-data/meta.yaml
Ref: https://github.com/astroconda/astroconda-dev/pull/177
> webbpsf-data: Prevent spurious 'work/' directory (#177)

- webbpsf-data/meta.yaml
Update data for the new WebbPSF release of version 0.8.0
> Update webbpsf-data for 0.8.0

- spectral-cube/bld.bat
- spectral-cube/build.sh
- spectral-cube/meta.yaml
> spectral-cube: Update 0.4.3

- imexam/meta.yaml
version has been pushed to pypi and tagged on master
@jhunkeler or @rendinam
> update imexam from 0.8.0 to 0.8.1

- spherical-geometry/meta.yaml
> spherical-geometry: Update 1.2.6

- tweakwcs/meta.yaml
See https://github.com/spacetelescope/tweakwcs/pull/34
CC: @jhunkeler
> tweakwcs bug-fix release 0.2.0

- stsci/meta.yaml
Rebuild `stsci` to accommodate DA5
> stsci: Update DA

- gwcs/meta.yaml
> update gwcs to latest release - 0.10.0

- tweakwcs/meta.yaml
See https://github.com/spacetelescope/tweakwcs/pull/46 for more details.
CC: @jhunkeler
> Bug fix for non-weighted fit RMSD computation

- tweakwcs/meta.yaml
See https://github.com/spacetelescope/tweakwcs/pull/47 and https://github.com/spacetelescope/tweakwcs/pull/49 but also `RMSD->RMSE` renaming and `MAE` computation.
> Bug fix release of tweakwcs

- stsci.skypac/meta.yaml
> Remove support for Py2

- stsci.skypac/meta.yaml
https://github.com/spacetelescope/stsci.skypac/pull/44
https://github.com/spacetelescope/stsci.skypac/pull/43
> stsci.skypac: 1.0.0 -> 1.0.1

- tweakwcs/meta.yaml
See https://github.com/spacetelescope/tweakwcs/pull/57
> Significantly redesigned tweakwcs API

- stsci.imagestats/meta.yaml
See https://github.com/spacetelescope/stsci.imagestats/pull/15
@jhunkeler
> Removed Python 2 suport

- tweakwcs/meta.yaml
See https://github.com/spacetelescope/tweakwcs/pull/59 for more details
> tweakwcs: delete debug print statements - code cleanup

- tweakwcs/meta.yaml
See https://github.com/spacetelescope/tweakwcs/pull/60 for more details.
CC: @jhunkeler
> tweakwcs: Bug fix release

- spherical-geometry/meta.yaml
Info:
https://github.com/spacetelescope/spherical_geometry/pull/161
> spherical_geometry 1.2.6 -> 1.2.8

- spherical-geometry/meta.yaml
https://github.com/spacetelescope/spherical_geometry/pull/163
https://github.com/spacetelescope/spherical_geometry/pull/164
> spherical_geometry -> 1.2.9

- stsci.skypac/bld.bat
- stsci.skypac/build.sh
- stsci.skypac/meta.yaml
* Update recipe
* Do not preserve egg
* Externally managed
> stsci.skypac: 1.0.2

- tweakwcs/bld.bat
- tweakwcs/build.sh
- tweakwcs/meta.yaml
* Update recipe
* Remove unused build dependencies
* Externally managed
> tweakwcs: 0.4.3

- stsci.image/bld.bat
- stsci.image/build.sh
- stsci.image/meta.yaml
* Update recipe
* Do not preserve egg
* Externally managed
> stsci.image: 2.3.1

- stsci.imagestats/bld.bat
- stsci.imagestats/build.sh
- stsci.imagestats/meta.yaml
* Update recipe
* Do not preserve egg
* Externally managed
> stsci.imagestats: 1.6.1

- dust_extinction/bld.bat
- dust_extinction/build.sh
- dust_extinction/meta.yaml
1st attempt at setting up the astropy affiliated dust_extinction package for astroconda.  Never done this before, so review definitely needed!
> Adding in info for dust_extinction package

- tweakwcs/meta.yaml
See https://github.com/spacetelescope/tweakwcs/pull/67
CC: @jhunkeler
> Fix incorrect pointer type

- stsci.convolve/bld.bat
- stsci.convolve/build.sh
- stsci.convolve/meta.yaml
- stsci.distutils/bld.bat
- stsci.distutils/build.sh
- stsci.imagemanip/bld.bat
- stsci.imagemanip/build.sh
- stsci.imagemanip/meta.yaml
- stsci.ndimage/bld.bat
- stsci.ndimage/build.sh
- stsci.ndimage/meta.yaml
- stsci.skypac/meta.yaml
- stsci.sphinxext/bld.bat
- stsci.sphinxext/build.sh
- stsci.sphinxext/meta.yaml
- stsci.stimage/bld.bat
- stsci.stimage/build.sh
- stsci.stimage/meta.yaml
- stsci.tools/bld.bat
- stsci.tools/build.sh
- stsci.tools/meta.yaml
* Remove `preserve_egg_dir`
* Use single version externally managed
> stsci.* namespace revamp:

- synphot/meta.yaml
See https://github.com/spacetelescope/synphot_refactor/releases/tag/0.1.3 for change log.
cc @tddesjardins
> Bump synphot to 0.1.3

- stsci.imagestats/meta.yaml
Refers to...
https://github.com/spacetelescope/stsci.imagestats/pull/20
https://github.com/spacetelescope/stsci.imagestats/pull/21
> stsci.imagestats: 1.6.2

- cubeviz/meta.yaml
Updated the yaml file to use 0.3.
> Updated for cubeviz release 0.3

- drizzle/bld.bat
- drizzle/build.sh
- drizzle/meta.yaml
Ref: https://github.com/spacetelescope/drizzle/pull/44
> drizzle: Update 1.12 -> 1.13

- tweakwcs/meta.yaml
Numerous improvements, bug fixes, code clean-up and unit tests.
CC: @jhunkeler @rendinam Also, please make a `pypi` release
> tweakwcs v0.5.0

- tweakwcs/meta.yaml
Bug fix in 2D-histogram initial shift estimation - see https://github.com/spacetelescope/tweakwcs/pull/90 for more details
CC: @jhunkeler
> Bug fix in 2D-histogram intitial shift estimation

- stsci.skypac/meta.yaml
> stsci.skypac 1.0.3: Better handling of cases of non-overlaping images

- fitsblender/bld.bat
- fitsblender/build.sh
- fitsblender/meta.yaml
ref https://github.com/spacetelescope/fitsblender/pull/26
> fitsblender: 0.3.5

- stsci.tools/meta.yaml
Refs:
https://github.com/spacetelescope/stsci.tools/pull/106
https://github.com/spacetelescope/stsci.tools/pull/101
> stsci.tools -> 3.6.0

- calcos/bld.bat
- calcos/build.sh
- calcos/meta.yaml
Refs:
https://github.com/spacetelescope/calcos/pull/56
> calcos -> 3.3.7

- calcos/bld.bat
- calcos/build.sh
- calcos/meta.yaml
Reverts astroconda/astroconda-contrib#526
> Revert "calcos -> 3.3.7"

- hstcal/meta.yaml
https://github.com/spacetelescope/hstcal/commits/2.3.0rc1
> hstcal -> 2.3.0rc1

- spherical-geometry/bld.bat
- spherical-geometry/build.sh
- spherical-geometry/meta.yaml
https://github.com/spacetelescope/spherical_geometry/pull/177
https://github.com/spacetelescope/spherical_geometry/pull/176
> spherical_geometry -> 1.2.14

- pysiaf/meta.yaml
This PR updates the version of pysiaf to 0.4.0
> Update pysiaf 0.1.8 -> 0.4.0

- ci-watson/meta.yaml
https://github.com/spacetelescope/ci_watson/releases/tag/0.4
Thanks for making the release, @jdavies-st !
> Bump ci-watson to 0.4

- spherical-geometry/meta.yaml
ref https://github.com/spacetelescope/spherical_geometry/pull/182
> spherical_geometry: 1.2.14 -> 1.2.16

- spherical-geometry/meta.yaml
ref: https://github.com/spacetelescope/spherical_geometry/pull/184
> spherical_geometry: 1.2.16 -> 1.2.17

- nictools/meta.yaml
ref: https://github.com/spacetelescope/nictools/pull/8
> nictools: 1.1.4 -> 1.1.5

- pysynphot/meta.yaml
ref: https://github.com/spacetelescope/pysynphot/pull/119
> pysynphot: 0.9.13 -> 0.9.14

- stregion/meta.yaml
ref:
https://github.com/spacetelescope/stregion/pull/7
https://github.com/spacetelescope/stregion/pull/8
> stregion: 1.1.4 -> 1.1.6

- stsci.stimage/meta.yaml
ref:
https://github.com/spacetelescope/stsci.stimage/pull/12
https://github.com/spacetelescope/stsci.stimage/pull/13
> stsci.stimage: 0.2.2 -> 0.2.4

- reftools/meta.yaml
https://pypi.org/project/reftools/
Tsk tsk, @jhunkeler
cc @sean-lockwood
> Bump reftools to 1.7.5

- pysiaf/meta.yaml
Update pysiaf version to 0.5.0
> pysiaf to v0.5.0

- ginga/meta.yaml
https://github.com/ejeschke/ginga/releases/tag/v3.0.1
> Bump Ginga to 3.0.1

- stwcs/meta.yaml
> stwcs release v 1.5.3

- specutils/meta.yaml
Increment specutils version from v0.5.2 to v0.6.
> Update specutils version

- astropy-healpix/meta.yaml
The new summary isn't particularly informative, but is based on the first line from https://astropy-healpix.readthedocs.io/en/latest/about.html#about
> Improve the summary for astropy-healpix

- spherical-geometry/meta.yaml
Ref: https://github.com/spacetelescope/spherical_geometry/pull/185
> spherical_geometry: 1.2.17 -> 1.2.18

- pysiaf/meta.yaml
Updating the `pysiaf` version and two new/updated package requirements to the `meta.yaml` file
tagging: @Johannes-Sahlmann
> Update pysiaf to v0.6.1

- crds/meta.yaml
For DMS 7.4 pre-release #2, supports additional NIRCAM CORONMSK values and fixes exception
handling for AWS S3-based reference file fetching.
> Updated version to crds 7.4.1.3 

- tweakwcs/meta.yaml
https://github.com/spacetelescope/tweakwcs/pull/94
CC: @jhunkeler
> Make new tweakwcs release (0.5.3)

- synphot/meta.yaml
https://github.com/spacetelescope/synphot_refactor/releases/tag/0.2.0
> Bump synphot to 0.2.0

- stsynphot/meta.yaml
https://github.com/spacetelescope/stsynphot_refactor/releases/tag/0.2.0
Depends on #574
> Bump stsynphot to 0.2.0

- poppy/meta.yaml
0.9.0
-----
*2019 Nov 22*
**New Functionality:**
* **Chaining together multiple propagations calculations:** Multiple `OpticalSystem` instances can now be chained together into a `CompoundOpticalSystem`. This includes mixed
propagations that are partially Fresnel and partially Fraunhofer; Wavefront objects will be cast between types as
needed. (:pr:`290` by :user:`mperrin`)
* **Gray pixel subsampling of apertures:** Implemented "gray pixel" sampling for circular apertures and stops, providing more precise models of aperture edges.
For circular apertures this is done  using a fast analytic geometry implementation adapted from open-source IDL code
originally by Marc Buie. (:pr:`325` by :user:`mperrin`, using Python code contributed by :user:`astrofitz`).
For subpixel / gray pixel sampling …
> Poppy v0.9.0

- pysiaf/meta.yaml
Updated package version and dependencies in meta.yaml file
> Pysiaf > 0.6.3

- stsynphot/meta.yaml
> Bump stsynphot to 0.2.1

- synphot/meta.yaml
> Bump synphot to 0.2.1

- extension-helpers/meta.yaml
- stsynphot/meta.yaml
- synphot/meta.yaml
> Add extension-helpers; modify [st]synphot recipes to match.

- stsynphot/meta.yaml
Same as the fix to `synphot` recipe.
> Add setuptools_scm to stsynphot build

- stsynphot/meta.yaml
> Bump stsynphot to 0.2.2

- stginga/meta.yaml
https://github.com/spacetelescope/stginga/releases/tag/1.1
> Bump stginga to 1.1

- ci-watson/meta.yaml
> Bump ci-watson to 0.5

- asdf/meta.yaml
> Bump asdf to 2.5.1

- tweakwcs/meta.yaml
Fixes a bug in alignment of multi-chip FITS WCS.
CC: @jhunkeler
> Release tweakwcs version 0.6.0

- ci-watson/meta.yaml
Hopefully this will make the package build.  One last time.
> Add requests as build dependency

- astroquery/meta.yaml
> Bump astroquery to 0.4

- cfitsio/meta.yaml
...because it has suddenly changed for no discernable reason.
> Update cfitsio download filename

- tweakwcs/meta.yaml
Fixes a bug in JWST corrector: when corrector model is updated, its inverse must be updated as well - see https://github.com/spacetelescope/tweakwcs/pull/112. Tweaked unit tests and added JWST alignment regression test: https://github.com/spacetelescope/tweakwcs/pull/113
CC: @jhunkeler
> Bug fix release for tweakwcs

- synphot/meta.yaml
https://github.com/spacetelescope/synphot_refactor/releases/tag/0.3
> Bump synphot to 0.3

- stsynphot/meta.yaml
https://github.com/spacetelescope/stsynphot_refactor/releases/tag/0.3
> Bump stsynphot to 0.3

- acstools/meta.yaml
ACS Team needs this for their new ACS Photometric CTE API.
cc @nmiles2718
> Bump acstools to 3.1

- imexam/bld.bat
- imexam/build.sh
- imexam/meta.yaml
> imexam: Update version (0.9.0) and recipe

- imexam/meta.yaml
> imexam: 0.9.0 -> 0.9.1

- jdat_notebooks/build.sh
- jdat_notebooks/meta.yaml
Version tag TBD
@jbcurtin @larrybradley
> Initial commit of jdat_notebooks

- stsci-data-analysis/meta.yaml
cc @larrybradley 
Local build showed no conflicts
> stsci-data-analysis: update floors

- tweakwcs/meta.yaml
https://github.com/spacetelescope/tweakwcs/pull/118
> Bug Fix: evaluate TP-to-TP transformation at origin for JWST

- asdf/meta.yaml
> Release asdf 2.6.0

- tweakwcs/meta.yaml
Bug fixes: https://github.com/spacetelescope/tweakwcs/pull/119, https://github.com/spacetelescope/tweakwcs/pull/120, and https://github.com/spacetelescope/tweakwcs/pull/122
CC: @jhunkeler
> tweakwcs release 0.6.4

- ds9/meta.yaml
Attempting to fix https://github.com/astroconda/astroconda/issues/86
> ds9: use conda openssl

- ginga/meta.yaml
- stginga/meta.yaml
> Bump ginga and stginga

- pysynphot/meta.yaml
Might wanna test this out first? I think pyproject.toml was added since the last release?
> Bump PySynphot to 1.0

- stsynphot/meta.yaml
- synphot/meta.yaml
> Bump synphot and stsynphot to 1.0

- synphot/meta.yaml
Hopefully this will fix build error on conda. Let me know if it doesn't.
> Bump synphot to 1.0.1

- tweakwcs/meta.yaml
Adds support for user-specified alignment tangent plane. See https://github.com/spacetelescope/tweakwcs/pull/125 for more information.
CC: @rendinam
> tweakwcs release 0.6.5

- asdf/meta.yaml
This is branched off of https://github.com/astroconda/astroconda-contrib/pull/659
> Release asdf 2.7.1

- jdat_notebooks/meta.yaml
> jdat_notebooks update to 0.2.0

- pysiaf/meta.yaml
Updating the `pysiaf` `meta.yaml` file for the new version `v0.10.0`
> Update pysiaf to v0.10.0

- gwcs/meta.yaml
Reverts astroconda/astroconda-contrib#678
> Revert "bump gwcs to 0.15.0"

- acstools/meta.yaml
https://github.com/spacetelescope/acstools/releases/tag/3.3.0
> Bump acstools to 3.3.1

- tweakwcs/meta.yaml
Added support for VA-corrected frames in JWST WCS, see https://github.com/spacetelescope/tweakwcs/pull/130
CC: @jhunkeler
> Release 0.7.1 of tweakwcs

- hstaxe/bld.bat
- hstaxe/build.sh
- hstaxe/meta.yaml
add hstaxe to the list of packages
> add hstaxe to package list

- jdat_notebooks/meta.yaml
> jdat_notebooks: update to 0.3.0

- jdat_notebooks/build.sh
- jdat_notebooks/meta.yaml
> jdat_notebooks: 0.3.0, take two

- jdat_notebooks/meta.yaml
> jdat_notebooks: 0.3.2

- hstcal/meta.yaml
> hstcal: 2.7.1

- ginga/meta.yaml
- stginga/meta.yaml
https://github.com/ejeschke/ginga/releases/tag/v3.2.0
https://github.com/spacetelescope/stginga/releases/tag/1.3.0
> MNT: Bump Ginga and stginga

- webbpsf-data/meta.yaml
- webbpsf/meta.yaml
This is a soft release for WebbPSF (v0.9.2)
> WebbPSF v0.9.2

- stsci.tools/meta.yaml
Changelog: https://github.com/spacetelescope/stsci.tools/blob/master/CHANGES.rst#400-2021-08-12
> Release stsci.tools v4.0.0

- tweakwcs/meta.yaml
Bug fixes and enhancements:
https://github.com/spacetelescope/tweakwcs/pull/143
https://github.com/spacetelescope/tweakwcs/pull/144
> Make tweakwcs release 0.7.3

- stsci.tools/meta.yaml
> Bump stsci.tools to 4.0.1

- jwebbinar_prep/meta.yaml
@jneu:  I think this fixes the recipe
> Fix recipe for jwebbinar_prep tag/version

- jdat_notebooks/meta.yaml
Needed for JWST DE-Build-E.
CC: @jneu
> Update jdat_notebooks to 0.4.0

- poppy/meta.yaml
Increase poppy version in meta.yaml
> Update poppy version

- pysiaf/meta.yaml
Update pysiaf's version to v0.15.0
> Update pysiaf version
